### ISSUE TITLE
Compile Error 

### ISSUE THREAD

**Issue by punkouter2021** [rahulsahay19/Movie-Review-SPA#1]
Severity    Code    Description Project File    Line    Suppression State
Error   CS1061  'DbSet<T>' does not contain a definition for 'Find' and no extension method 'Find' accepting a first argument of type 'DbSet<T>' could be found (are you missing a using directive or an assembly reference?)   MovieReviewSPA.Data..NET Framework 4.5.1, MovieReviewSPA.Data..NET Platform 5.4 C:\Users\punkouter\Source\Repos\Movie-Review-SPA\MovieReviewSPA.Data\EFRepository.cs    34  Active

**Comment by rahulsahay19** [comment]
I have already addressed this issue in the code. I have also mentioned the same in my blog. You can refer here. http://myview.rahulnivi.net/dbset-find-api-missing-entity-framework-core-final-rc1-version/

**Comment by rahulsahay19** [comment]
Also review Extensions file in Helpers folder and check the reference as well.
